//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.24 at 10:32:03 AM ICT 
//


package hieplh.jaxb.jobdetail;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for Details complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Details">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="address" type="{http://www.w3.org/2001/XMLSchema}token"/>
 *         &lt;element name="salary" type="{http://www.w3.org/2001/XMLSchema}token"/>
 *         &lt;element name="experience" type="{http://www.w3.org/2001/XMLSchema}token"/>
 *         &lt;element name="level" type="{http://www.w3.org/2001/XMLSchema}token"/>
 *         &lt;element name="provinces" type="{}Provinces"/>
 *         &lt;element name="careers" type="{}Careers"/>
 *         &lt;element name="recruitment" type="{http://www.w3.org/2001/XMLSchema}token"/>
 *         &lt;element name="gender" type="{http://www.w3.org/2001/XMLSchema}token"/>
 *         &lt;element name="natureOfWork" type="{http://www.w3.org/2001/XMLSchema}token"/>
 *         &lt;element name="formOfWork" type="{http://www.w3.org/2001/XMLSchema}token"/>
 *         &lt;element name="try" type="{http://www.w3.org/2001/XMLSchema}token"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Details", propOrder = {
    "address",
    "salary",
    "experience",
    "level",
    "provinces",
    "careers",
    "recruitment",
    "gender",
    "natureOfWork",
    "formOfWork",
    "_try"
})
public class Details implements Serializable{

    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String address;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String salary;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String experience;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String level;
    @XmlElement(required = true)
    protected Provinces provinces;
    @XmlElement(required = true)
    protected Careers careers;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String recruitment;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String gender;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String natureOfWork;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String formOfWork;
    @XmlElement(name = "try", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String _try;

    /**
     * Gets the value of the address property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddress(String value) {
        this.address = value;
    }

    /**
     * Gets the value of the salary property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSalary() {
        return salary;
    }

    /**
     * Sets the value of the salary property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSalary(String value) {
        this.salary = value;
    }

    /**
     * Gets the value of the experience property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExperience() {
        return experience;
    }

    /**
     * Sets the value of the experience property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExperience(String value) {
        this.experience = value;
    }

    /**
     * Gets the value of the level property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLevel() {
        return level;
    }

    /**
     * Sets the value of the level property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLevel(String value) {
        this.level = value;
    }

    /**
     * Gets the value of the provinces property.
     * 
     * @return
     *     possible object is
     *     {@link Provinces }
     *     
     */
    public Provinces getProvinces() {
        return provinces;
    }

    /**
     * Sets the value of the provinces property.
     * 
     * @param value
     *     allowed object is
     *     {@link Provinces }
     *     
     */
    public void setProvinces(Provinces value) {
        this.provinces = value;
    }

    /**
     * Gets the value of the careers property.
     * 
     * @return
     *     possible object is
     *     {@link Careers }
     *     
     */
    public Careers getCareers() {
        return careers;
    }

    /**
     * Sets the value of the careers property.
     * 
     * @param value
     *     allowed object is
     *     {@link Careers }
     *     
     */
    public void setCareers(Careers value) {
        this.careers = value;
    }

    /**
     * Gets the value of the recruitment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecruitment() {
        return recruitment;
    }

    /**
     * Sets the value of the recruitment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecruitment(String value) {
        this.recruitment = value;
    }

    /**
     * Gets the value of the gender property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGender() {
        return gender;
    }

    /**
     * Sets the value of the gender property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGender(String value) {
        this.gender = value;
    }

    /**
     * Gets the value of the natureOfWork property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNatureOfWork() {
        return natureOfWork;
    }

    /**
     * Sets the value of the natureOfWork property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNatureOfWork(String value) {
        this.natureOfWork = value;
    }

    /**
     * Gets the value of the formOfWork property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormOfWork() {
        return formOfWork;
    }

    /**
     * Sets the value of the formOfWork property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormOfWork(String value) {
        this.formOfWork = value;
    }

    /**
     * Gets the value of the try property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTry() {
        return _try;
    }

    /**
     * Sets the value of the try property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTry(String value) {
        this._try = value;
    }

}
